---
- name: Applying {{ item.aci_query_title | regex_replace('_', ' ') | upper }} Regular Expressions
  set_fact:
    aci_regexd: '{{ aci_filtered | regex_replace("(uni\/|infra\/|funcprof\/|accportgrp-|accbundle-|accportprof-|attentp-)") | regex_replace("infraAccPortGrp", "Access") | regex_replace("infraAccBndlGrp", "Bundle") | regex_replace("infraSpAccPortGrp", "Multipod") | regex_replace("fexprof-", "Fex Profile -> ") }}'
  tags: always
