---
- name: Applying {{ item.aci_query_title | regex_replace('_', ' ') | upper }} Regular Expressions
  set_fact:
    aci_regexd: '{{ aci_filtered | regex_replace("(uni\/tn-)") | regex_replace("(\/out-|\/lnodep-|\/lifp-|\/rspathL3OutAtt-\[topology\/pod-|\/paths-|\/pathep-\[|\/peerP-)", "|") }}'
  tags: always
