---
- name: Applying {{ item.aci_query_title | regex_replace('_', ' ') | upper }} Regular Expressions
  set_fact:
    aci_regexd: '{{ aci_filtered | regex_replace("(uni\/|tn-)") | regex_replace("(\/ap-|\/epg-|\/rscons-|\/out-|\/instP-|\/mgmtp-|\/inb-)", "|") }}'
  tags: always
