---
- name: Applying {{ item.aci_query_title | regex_replace('_', ' ') | upper }} Regular Expressions
  set_fact:
    aci_regexd: '{{ aci_filtered | regex_replace("(topology\/pod-|\/sys\/ctrlrfwstatuscont\/ctrlrrunning)") | regex_replace("(\/node-)", "|") }}'
  tags: always
