---
- name: Applying {{ item.aci_query_title | regex_replace('_', ' ') | upper }} Regular Expressions
  set_fact:
    aci_regexd: '{{ aci_filtered | regex_replace("(uni\/|infra\/|vlanns-|attentp-|tn-|-dynamic|-static)") | regex_replace("\/out-", ":") }}'
  tags: always
