---
- name: Applying {{ item.aci_query_title | regex_replace('_', ' ') | upper }} Regular Expressions
  set_fact:
    aci_regexd: '{{ aci_filtered | regex_replace("(topology\/pod-|)") | regex_replace("(\/node-|\/sys\/ospf\/inst-|\/dom-|\/if-\[|\]\/adj-)", "|") }}'
  tags: always
