---
- name: Applying {{ item.aci_query_title | regex_replace('_', ' ') | upper }} Regular Expressions
  set_fact:
    aci_regexd: '{{ aci_filtered | regex_replace("(uni\/|infra\/|vlanns-|attentp-|tn-)") | regex_replace("]-", "|") | regex_replace("(\/ap-|\/epg-)", ":") }}'
  tags: always
